// <auto-generated />
using System;
using ClubeDaLeituraWeb.WebApp.Compartilhado.Infra.Orm;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubeDaLeituraWeb.WebApp.Migrations
{
    [DbContext(typeof(ListaDeComprasDbContext))]
    [Migration("20260803181551_ListaDeCompras")]
    partial class ListaDeCompras
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClubeDaLeituraWeb.WebApp.ModuloCategoria.Dominio.Categoria", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cor")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_TBCategoria");

                    b.ToTable("TB_Categorias", (string)null);
                });

            modelBuilder.Entity("ClubeDaLeituraWeb.WebApp.ModuloItensProduto.Dominio.ItensProduto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ItensProdutoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProdutoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuantidadeProduto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItensProdutoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensProdutos");
                });

            modelBuilder.Entity("ClubeDaLeituraWeb.WebApp.ModuloListaDeCompra.Dominio.ListaDeCompra", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StatusLista")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_ListaDeCompras");

                    b.ToTable("TB_ListaDeCompras", (string)null);
                });

            modelBuilder.Entity("Produto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoriaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecoAproximado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_TBProduto");

                    b.HasIndex("CategoriaId");

                    b.ToTable("TB_Produto", (string)null);
                });

            modelBuilder.Entity("ClubeDaLeituraWeb.WebApp.ModuloItensProduto.Dominio.ItensProduto", b =>
                {
                    b.HasOne("ClubeDaLeituraWeb.WebApp.ModuloListaDeCompra.Dominio.ListaDeCompra", "ListaDeCompra")
                        .WithMany("Produtos")
                        .HasForeignKey("ItensProdutoId")
                        .HasConstraintName("FK_TBListaDeCompras_TBItensProduto");

                    b.HasOne("Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");

                    b.Navigation("ListaDeCompra");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Produto", b =>
                {
                    b.HasOne("ClubeDaLeituraWeb.WebApp.ModuloCategoria.Dominio.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TBProduto_TBCategoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ClubeDaLeituraWeb.WebApp.ModuloCategoria.Dominio.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("ClubeDaLeituraWeb.WebApp.ModuloListaDeCompra.Dominio.ListaDeCompra", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
