// <auto-generated />
using System;
using ClubeDaLeituraWeb.WebApp.Compartilhado.Infra.Orm;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubeDaLeituraWeb.WebApp.Migrations
{
    [DbContext(typeof(ListaDeComprasDbContext))]
    partial class ListaDeComprasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClubeDaLeituraWeb.WebApp.ModuloCategoria.Dominio.Categoria", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cor")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_TBCategoria");

                    b.ToTable("TB_Categorias", (string)null);
                });

            modelBuilder.Entity("ClubeDaLeituraWeb.WebApp.ModuloItensProduto.Dominio.ItensProduto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ListaDeCompraId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProdutoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuantidadeProduto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ListaDeCompraId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensProdutos");
                });

            modelBuilder.Entity("ClubeDaLeituraWeb.WebApp.ModuloListaDeCompra.Dominio.ListaDeCompra", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusLista")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ListasDeCompras");
                });

            modelBuilder.Entity("Produto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoriaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoAproximado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("ClubeDaLeituraWeb.WebApp.ModuloItensProduto.Dominio.ItensProduto", b =>
                {
                    b.HasOne("ClubeDaLeituraWeb.WebApp.ModuloListaDeCompra.Dominio.ListaDeCompra", null)
                        .WithMany("ListaProdutos")
                        .HasForeignKey("ListaDeCompraId");

                    b.HasOne("Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Produto", b =>
                {
                    b.HasOne("ClubeDaLeituraWeb.WebApp.ModuloCategoria.Dominio.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ClubeDaLeituraWeb.WebApp.ModuloListaDeCompra.Dominio.ListaDeCompra", b =>
                {
                    b.Navigation("ListaProdutos");
                });
#pragma warning restore 612, 618
        }
    }
}
